<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
    <OutputType>Library</OutputType>
    <RootNamespace>ShareX.ImageEditor</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\closedhand.cur" />
    <AvaloniaResource Include="Assets\Crosshair.cur" />
    <AvaloniaResource Include="Assets\lucide.ttf" />
    <AvaloniaResource Include="Assets\openhand.cur" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>
</Project>
